// electron-builder afterPack hook: assert the packaged app really carries every
// license notice it is supposed to.
//
// Table Viewer is GPL-3.0 and ships four files in the packaged app's resources
// directory: LICENSE.txt (ours), THIRD_PARTY_NOTICES.txt (generated by
// desktop/collect-licenses.mjs), and Electron's own LICENSE.electron.txt +
// LICENSES.chromium.html, all placed by `extraResources` in
// electron-builder.yml.
//
// The check exists because a missing `extraResources` source is only a WARNING
// in electron-builder, not an error: a half-installed node_modules/electron
// (Electron's postinstall skipped or interrupted, so dist/ has no LICENSE files)
// produces a perfectly normal-looking installer with the attributions silently
// missing. That is exactly the kind of thing nobody notices until it ships, so
// fail the build here instead.
import { stat } from 'node:fs/promises';
import { join } from 'node:path';

// Contents/Resources destinations from electron-builder.yml's extraResources.
const REQUIRED_NOTICES = [
    'LICENSE.txt',
    'THIRD_PARTY_NOTICES.txt',
    'LICENSE.electron.txt',
    'LICENSES.chromium.html',
];

// Where extraResources land, per platform. macOS buries them in the .app
// bundle; Windows and Linux put them in a sibling `resources` directory.
function resources_dir(context) {
    if (context.electronPlatformName === 'darwin') {
        return join(
            context.appOutDir,
            `${context.packager.appInfo.productFilename}.app`,
            'Contents',
            'Resources',
        );
    }
    return join(context.appOutDir, 'resources');
}

export default async function after_pack(context) {
    const resources = resources_dir(context);

    const missing = [];
    for (const name of REQUIRED_NOTICES) {
        try {
            // Empty counts as missing: a zero-byte notice is no notice.
            if ((await stat(join(resources, name))).size === 0) missing.push(`${name} (empty)`);
        } catch {
            missing.push(name);
        }
    }

    if (missing.length > 0) {
        throw new Error(
            `Packaged app is missing required license notices: ${missing.join(', ')}.\n` +
                'These come from extraResources in desktop/electron-builder.yml, whose sources ' +
                'include node_modules/electron/dist/. If the Electron ones are missing, that ' +
                "install is incomplete — check that node_modules/electron/path.txt exists and " +
                'dist/ is a full extraction (~270M), then reinstall:\n' +
                '  rm -rf node_modules/electron && npm ci',
        );
    }
}
